### ISSUE TITLE
dpath version above 2.0.6

### ISSUE THREAD

**Issue by flnphil** [ndejong/elasticsearch_kibana_cli#2]
dpath versions greater than 2.0.6 seems to be causing too many search results in python 3.9 and higher.

**Comment by ndejong** [comment]
Hi thanks for the submission, not quite enough information here to follow this (yet) - could you provide more detail in what you are seeing and an example

**Comment by flnphil** [comment]
Thanks. 
Notable difference is the presence of some extra payloads generated in  ElasticsearchKibanaCLISearch.msearch and __payload_range_splitter when using dpath 2.1.6. 

For instance  

```
elasticsearch_kibana_cli:

  base_uri: my_endpoint

  search_definitions: 
    default_search: 
      index: '*'
      splits: 10 
      source:
        - "_id" 
      search: 
        must:
          range:
            @timestamp: 
              'lte': '2023-01-01 01:00:00.000'
              'gte': '2023-01-01 02:00:00.000' 
          query_string:
            - query: "request:*keyword*"
```

The above search configuration  adds something like these 10 lines of payload in dpath 2.1.6 which I did not see in dpath 2.0.6.
```
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": }}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": ?, "gte": ?}}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": ?, "gte": ?}}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": ?, "gte": ?}}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": ?, "gte": ?}}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": ?, "gte": ?}}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": ?, "gte": ?}}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": ?, "gte": ?}}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"lt": ?, "gte": ?}}}]}}}
{"query": {"bool": {"must": [{"range": {"@timestamp": {"gte": ?}}}]}}}
```
